apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-service-discovery-controller
  namespace: kube-monitor
  labels:
    app.kubernetes.io/name: nacos-service-discovery-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nacos-service-discovery-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nacos-service-discovery-controller
    spec:
      containers:
      - name: nacos-service-discovery-controller
        image: reg.flashexpress.com/library/nacos-service-discovery-controller:0.2.0
        imagePullPolicy: Always
        args:
          - exporter 
          - --nacosIpAddr=nacos-cs.basic-components
          - --nacosUsername=nacos 
          - --nacosPassword=nacos
        ports:
        - name: http
          containerPort: 8428
          protocol: TCP
        resources:
          limits:
            cpu: 4
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthy
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 10
